# Generated by Django 4.0.4 on 2022-05-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_requirements',
        ),
    ]
