# Generated by Django 4.0.4 on 2022-05-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostings', '0003_rename_job_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
