# Generated by Django 4.0.4 on 2022-05-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPostings', '0004_alter_jobs_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
